development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: nlims
  suffix: repo_
  username: root
  password: root

test:
  <<: *development
  suffix: test

production:
  <<: *development
  protocol: 'http'
