development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: nlims
  suffix: repo
  username: root
  password: amin9090!
test:
  <<: *development
  suffix: test

production:
  <<: *development
  protocol: 'http'
